INSERT INTO books (name, author, description, isbn, image_name)
VALUES
       -- Programming Books
       ('Clean Code: A Handbook of Agile Software Craftsmanship',
        'Robert C. Martin Series',
        'Even bad code can function. But if code isn’t clean, it can bring a development organization to its knees.',
        '9780132350884',
        'clean_code.jpg'),
       ('Clean Coder: A Handbook of Agile Software Craftsmanship',
        'Robert C. Martin Series',
        'Programmers who endure and succeed amidst swirling uncertainty and nonstop pressure share a common attribute: They care deeply about the practice of creating software. They treat it as a craft. They are professionals.',
        '9780137081073',
        'clean_coder.jpg'),
        ('Effective Java',
        'Joshua Bloch',
        'Comprehensive coding practices for writing robust and modern Java programs.',
        '9780134685991',
        'effective_java.jpg'),
       ('The Go Programming Language',
        'Alan A. A. Donovan and Brian W. Kernighan',
        'A thorough introduction to programming with GoLang.',
        '9780134190440',
        'go_programming_language.jpg'),
       ('Learning React',
        'Alex Banks and Eve Porcello',
        'A hands-on guide to building web interfaces using React.',
        '9781491954621',
        'learning_react.jpg'),
       ('Next.js in Action', 'Liang Yi',
        'Learn to build scalable and fast web applications with Next.js.',
        '9781617297343',
        'next_js_in_action.jpg'),
       ('AWS Certified Solutions Architect Study Guide',
        'Ben Piper',
        'Master Amazon Web Services solution delivery and efficiently prepare for the AWS Certified SAA-C03 Exam with this all-in-one study guide',
        '9781119982623',
        'aws_certified_solution_architect.jpg'),
       ('Learning Microsoft Azure: Cloud Computing and Development Fundamentals',
        'Jonah Carrio Andersson',
        'If your organization plans to modernize services and move to the cloud from legacy software or a private cloud on premises, this book is for you.',
        '9781098113322',
        'learning_microsoft_azure.jpg'),
        ('Effective Angular: Develop applications of any size by effectively using Angular',
        'Roberto Heckers',
        'Develop your front-end expertise and build scalable, enterprise-ready web applications by efficiently using the Angular framework''s powerful features and essential libraries.',
        '9781805125532',
        'effective_angular.jpg'),
        ('Scala for the Impatient',
        'Cay S. Horstmann',
        'Scala 3 is concise, consistent, flexible, robust, and efficient, but there''s a lot to learn and navigating features and improvements can be challenging.',
        '9780138033651',
        'scala_for_the_impatient.jpg'),
        ('Kafka: The Definitive Guide: Real-Time Data and Stream Processing at Scale',
        'Gwen Shapira',
        'Every enterprise application creates data, whether it consists of log messages, metrics, user activity, or outgoing messages. Moving all this data is just as important as the data itself. ',
        '97801492043089',
        'kafka_the_definition_edition.jpg')
;